analysis:
  raw: $SCRATCH/SALMON/raw_data/analysis/analysis_bucket
  moose: moose:/opfc/atm/global/prods/
  temp: $SCRATCH/SALMON/temp
  query: $HOME/MJO/SALMON/RETRIEVALS/analysis_combined.query
  processed: $SCRATCH/SALMON/processed_SEA_data/analysis
  archive: $DATADIR/SALMON/processed_SEA_data/analysis
  plots: $DATADIR/SALMON/processed_SEA_data/analysis

mogreps:
  raw: $SCRATCH/SALMON/raw_data/mogreps/mogreps_bucket
  moose: moose:/opfc/atm/mogreps-g/prods/
  temp: $SCRATCH/SALMON/temp
  processed: $SCRATCH/SALMON/processed_SEA_data/mogreps
  archive: $DATADIR/SALMON/processed_SEA_data/mogreps
  plots: $SCRATCH/SALMON/processed_SEA_data/mogreps
  mock_retrieval: False

glosea:
  raw: $SCRATCH/SALMON/raw_data/glosea/glosea_bucket
  moose: moose:/opfc/atm/glosea/prods/
  processed: $SCRATCH/SALMON/processed_SEA_data/glosea
  archive: $DATADIR/SALMON/processed_SEA_data/glosea
  plots: $SCRATCH/SALMON/processed_SEA_data/glosea

gpm:
  raw: /data/users/gpm_imerg/NRTlate/current_version/postprocessed_daily
  processed: $SCRATCH/SALMON/processed_SEA_data/gpm
  archive: $DATADIR/SALMON/processed_SEA_data/gpm
  plots: $DATADIR/SALMON/processed_SEA_data/gpm

ifs:
  raw: /data/scratch/julian.heming/GRIB/ECMWF
  temp: $SCRATCH/SALMON/temp
  processed: $SCRATCH/SALMON/processed_SEA_data/ifs
  archive: $DATADIR/SALMON/processed_SEA_data/ifs
  plots: $DATADIR/SALMON/processed_SEA_data/ifs

global:
  forecast_out_dir: $SCRATCH/SALMON/processed_SEA_data/mogreps
  map_outline_json_file: $HOME/MJO/MJO/SALMON_v2/SALMON_CORE/utils/map_files/map_outline.json
